config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :matters
  resources :teachers
  resources :students
  resources :courses
  get 'add_course_matters', to: 'courses#add_matters'
  post 'save_course_matters', to: 'courses#save_matters'
  get 'add_student_courses', to: 'students#add_courses'
  post 'save_student_courses', to: 'students#save_courses'
  get 'add_note', to: 'students#add_note'
  post 'students/save_note'
  root to: 'teachers#index'
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
    get 'students', to: 'students#list'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
	validates_presence_of :name

	def save_matters(matter_ids)
		m_ids = matter_ids.values
		return false if m_ids.size <= 0
		Course.transaction do
			begin
				m_ids.each do |mi|
					cm = CourseMatter.new
					cm.course_id = self.id
					cm.matter_id = mi.to_i
					cm.save!
				end
				return true
			rescue Exception => e
				return false
			end
		end
	end
end

app/models/course_matter.rb
class CourseMatter < ApplicationRecord
	belongs_to :matter
	belongs_to :course
	validates_presence_of :matter, :course
	validates :matter, uniqueness: { scope: :course }
end

app/models/course_student.rb
class CourseStudent < ApplicationRecord
	belongs_to :student
	belongs_to :course
	validates_presence_of :student, :course
end

app/models/matter.rb
class Matter < ApplicationRecord
	validates_presence_of :name
end

app/models/note.rb
class Note < ApplicationRecord
	belongs_to :student
	belongs_to :course
	belongs_to :matter, foreign_key: 'matter_id'
	validates_presence_of :student, :course, :point, :matter_id
	validates_numericality_of :matter_id, :greater_than_or_equal_to => 1

	def as_json(options = {})
		h = options
		h['calificacion'] = self.point
		h['curso'] = self.course.name
		h['asignatura'] = self.matter.name
		h
	end

	def add_point(point)
		point = point.to_i
		if point <= 0
			self.errors.add(:point, "Calificación no debe ser mayor que 0")
			return
		end
		total_students = Student.count
		current_minute = DateTime.now.minute
		max_point = total_students + current_minute
		if point > max_point
			self.errors.add(:point, "Calificación no debe superar #{max_point}")
		else
			self.point = point
		end
	end
end

app/models/student.rb
class Student < ApplicationRecord
	validates_presence_of :name
	has_many :notes
	has_many :course_students
	has_many :courses, through: :course_students

	def as_json(options = { })
		h = options
		h['name'] = self.name
		h['notes'] = self.notes.as_json
		h
	end

	def save_courses(courses_ids)
		c_ids = courses_ids.values
		return false if c_ids.size <= 0
		Student.transaction do
			begin
				c_ids.each do |mi|
					cm = CourseStudent.new
					cm.course_id = self.id
					cm.student_id = mi.to_i
					cm.save!
				end
				return true
			rescue Exception => e
				return false
			end
		end
	end

	def save_note(params)
		errors = []
		Student.transaction do
			begin
				note = Note.new
				note.add_point(params[:point])
				note.course_id = params[:course_id].to_i
				note.matter_id = params[:matter_id].to_i
				note.student_id = self.id
				if note.errors.full_messages.present?
					errors = erros + note.errors.full_messages.to_a
				end
				if note.save!
					return {saved: true, errors: []}
				end

			rescue Exception => e
				errors = errors + note.errors.full_messages
				return {saved: false, errors: errors}
			end
		end
	end
end

app/models/teacher.rb
class Teacher < ApplicationRecord
	validates_presence_of :name
end

app/controllers/api/v1/students_controller.rb
module Api
	module V1
		class StudentsController < ApplicationController
			def list
				render json: {students: Student.all.as_json}, status: 200
			end
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
	def index
		@courses = Course.all
	end

	def new
		@course = Course.new
	end

	def create
		@course = Course.new(course_params)
		if @course.save
			redirect_to courses_path
		else
			render :new
		end
	end

	def add_matters
		@matters = Matter.all
		@course = Course.find(params[:id])
	end

	def save_matters
		@course = Course.find(params[:course_id])
		if @course.save_matters(params[:matters])
			redirect_to courses_path
		else
			@matters = Matter.all
			render :add_matters
		end
	end

	private
	def course_params
		params.require(:course).permit(:name)
	end
end

app/controllers/matters_controller.rb
class MattersController < ApplicationController
	def index
		@matters = Matter.all
	end

	def new
		@matter = Matter.new
	end

	def create
		@matter = Matter.new(matter_params)
		if @matter.save
			redirect_to matters_path
		else
			render :new
		end
	end

	private
	def matter_params
		params.require(:matter).permit(:name)
	end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	def index
		@students = Student.all
	end

	def new
		@student = Student.new
	end

	def create
		@student = Student.new(student_params)
		if @student.save
			redirect_to students_path
		else
			render :new
		end
	end

	def add_courses
		@courses = Course.all
		@student = Student.find(params[:id])
	end

	def save_courses
		@student = Student.find(params[:student_id])
		if @student.save_courses(params[:courses])
			redirect_to courses_path
		else
			@courses = Course.all
			render :add_courses
		end
	end

	def add_note
		@student = Student.find(params[:id])
		@courses = @student.courses
		@matters = Matter.all
	end

	def save_note
		@student = Student.find(params[:student_id])
		response = @student.save_note(params)
		if response[:saved]
			redirect_to students_path
		else
			@errors = response[:errors]
			@courses = @student.courses
			@matters = Matter.all
			render :add_note
		end
	end

	private
	def student_params
		params.require(:student).permit(:name)
	end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
	def index
		@teachers = Teacher.all
	end

	def new
		@teacher = Teacher.new
	end

	def create
		@teacher = Teacher.new(teacher_params)
		if @teacher.save
			redirect_to teachers_path
		else
			render :new
		end
	end

	private
	def teacher_params
		params.require(:teacher).permit(:name)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/courses/add_matters.haml
%h2 Agregar Materias
/ - matters = @course.matters
= form_tag save_course_matters_path, method: :post do
	= hidden_field_tag :course_id, @course.id
	%table
		- @matters.each do |matter|
			%tr
				= check_box_tag "matters[#{matter.id}]", matter.id
				%span= matter.name
	= button_tag :submit do
		Guardar

app/views/courses/index.haml
%h2 Cursos

= link_to 'Nuevo', new_course_path

- if @courses.present?
	%table
		%tr
			%th Id
			%th Nombre
			%th{nowrap: 'nowrap'}
		%tr
			- @courses.each do |co|
				%tr
					%td= co.id
					%td= co.name
					%td
						= link_to 'Agregar materia', add_course_matters_path(id: co.id)

app/views/courses/new.haml
%h2 Nuevo curso
- if @course.errors.present?
	%label Por favor revisa lo siguiente:
	- @course.errors.full_messages.each do |ms|
		%p= ms
= form_for @course do |f|
	.name_field
		= f.label :name, 'Nombre*'
		= f.text_field :name
	.action
		= f.submit 'Guardar'

app/views/layouts/application.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title School
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render partial: 'partials/nav'
    = yield

app/views/matters/index.haml
%h2 Asignaturas

= link_to 'Nueva', new_matter_path

- if @matters.present?
	%table
		%tr
			%th Id
			%th Nombre
		%tr
			- @matters.each do |co|
				%tr
					%td= co.id
					%td= co.name

app/views/matters/new.haml
%h2 Nueva materia
- if @matter.errors.present?
	%label Por favor revisa lo siguiente:
	- @matter.errors.full_messages.each do |ms|
		%p= ms
= form_for @matter do |f|
	.name_field
		= f.label :name, 'Nombre*'
		= f.text_field :name
	.action
		= f.submit 'Guardar'

app/views/partials/_nav.haml
= link_to 'Estudiantes', students_path
= link_to 'Profesores', teachers_path
= link_to 'Asignaturas', matters_path
= link_to 'Cursos', courses_path

app/views/students/add_courses.haml
%h2 Agregar Cursos
/ - matters = @course.matters
= form_tag save_student_courses_path, method: :post do
	= hidden_field_tag :student_id, @student.id
	%table
		- @courses.each do |course|
			%tr
				= check_box_tag "courses[#{course.id}]", course.id
				%span= course.name
	= button_tag :submit do
		Guardar

app/views/students/add_note.haml
%h2 Agregar nota
%label="Estudiante #{@student.name}"
- if @errors.present? 
	- @errors.each do |err|
		%p= err
= form_tag students_save_note_path, method: :post do
	= hidden_field_tag :student_id, @student.id
	.point-container
		= label_tag 'Calificación*'
		= number_field_tag :point
	.course-container
		= label_tag 'Curso*'
		= select_tag :course_id, options_from_collection_for_select(@courses, "id", "name", @course_id), include_blank: true
	.matter-container
		= label_tag 'Asignatura*'
		= select_tag :matter_id, options_from_collection_for_select(@matters, "id", "name", @matter_id), include_blank: true
	.action
		= submit_tag :submit do
			Guardar

app/views/students/index.haml
%h2 Estudiantes

= link_to 'Nuevo', new_student_path
- if @students.present?
	%table
		%tr
			%th Id
			%th Nombre
			%th{nowrap: 'nowrap'}
		%tr
			- @students.each do |co|
				%tr
					%td= co.id
					%td= co.name
					%td
						= link_to 'Agregar Curso', add_student_courses_path(id: co.id)
						= link_to 'Agregar Nota', add_note_path(id: co.id)

app/views/students/new.haml
%h2 Nuevo curso
- if @student.errors.present?
	%label Por favor revisa lo siguiente:
	- @student.errors.full_messages.each do |ms|
		%p= ms
= form_for @student do |f|
	.name_field
		= f.label :name, 'Nombre*'
		= f.text_field :name
	.action
		= f.submit 'Guardar'

app/views/teachers/index.haml
%h2 Profesores

= link_to 'Nuevo', new_teacher_path

- if @teachers.present?
	%table
		%tr
			%th Id
			%th Nombre
		%tr
			- @teachers.each do |co|
				%tr
					%td= co.id
					%td= co.name

app/views/teachers/new.haml
%h2 Nuevo curso
- if @teacher.errors.present?
	%label Por favor revisa lo siguiente:
	- @teacher.errors.full_messages.each do |ms|
		%p= ms
= form_for @teacher do |f|
	.name_field
		= f.label :name, 'Nombre*'
		= f.text_field :name
	.action
		= f.submit 'Guardar'